### ISSUE TITLE
Receive read results as List<T> type (T is user defined type)

### ISSUE THREAD

**Issue by doyaaaaaken** [doyaaaaaken/kotlin-csv#21]

**Comment by blackmo18** [comment]
Some time ago I made this [kotlin-grass](https://github.com/blackmo18/kotlin-grass) and its using kotlin-csv also. The down side on what I made i think, it is dependent on kotlin-csv result before it processes into user-defined class.

**Comment by doyaaaaaken** [comment]
Resolved by above discussion.
