### ISSUE TITLE
Write Without Header

### ISSUE THREAD

**Issue by devKshitijJain** [doyaaaaaken/kotlin-csv#39]
With current implementation whenever we write rows, it automatically adds the first row as a header. There should be an option to say no header needed.

**Comment by doyaaaaaken** [comment]
Hi, @devKshitijJain. Thank you your great feedback!

I think it would be nice to implement `withoutHeader` option like below.
([Document Link about Writer Option](https://github.com/doyaaaaaken/kotlin-csv#customize-1))

```
val writer = csvWriter {
    withoutHeader = true
}
writer.open("test.csv") { writeAll(rows) }
```

If you could help to implement this, feel free to send pull request.

**Comment by doyaaaaaken** [comment]
I will work on this.

**Comment by doyaaaaaken** [comment]
I investigated current specification, and I noticed my previous comment https://github.com/doyaaaaaken/kotlin-csv/issues/39#issuecomment-607021209 is wrong.
I had mistaken the library's behavior.

As investigation, I wrote below code.

```kotlin
val rows = listOf(listOf("a", "b", "c"), listOf("d", "e", "f"))
csvWriter().open("test.csv") { writeAll(rows) }
```

Then I got a csv file below.
```csv
a,b,c
d,e,f

```

So, as current behavior, kotlin-csv doesn't add the first row as header.
If you'd like to add header, you should write like below.
```
val header = listOf("column1", "column2", "column3")
val rows = listOf(listOf("a", "b", "c"), listOf("d", "e", "f"))
csvWriter().open("test2.csv") {
    writeRow(header)
    writeAll(rows)
}
```
