### ISSUE TITLE
Ability to read line by line file with header

### ISSUE THREAD

**Issue by Dogzik** [doyaaaaaken/kotlin-csv#40]
It is very common to have csv headers in csv files. However not always I can or need to store the whole file in memory. Right now there is possibility either to read file line by line or read all data with header. It would be really useful to be able to do both at the same time

**Comment by doyaaaaaken** [comment]
Thank you so much for your valuable advice!

I agree your opinition, and I think we need below method.
`fun readWithHeaderAsSequence(): Sequence<Map<String, String>>`

**Comment by Dogzik** [comment]
Yeah, sounds just as I imagined it

**Comment by doyaaaaaken** [comment]
Great job @blackmo18 ! Changes are included in version 0.8.0.
