### ISSUE TITLE
Skip mismatched row fields number option?

### ISSUE THREAD

**Issue by IllusionMan1212** [doyaaaaaken/kotlin-csv#42]
Is it possible to add an option to skip (or even read) rows with different fields number than other rows instead of throwing an exception. I'm willing to PR it myself if you're open to adding this option

Let me know what your thoughts are on this

**Comment by doyaaaaaken** [comment]
Thanks for your proposal 👍  Let me confirm if I got it.

If we read below csv file with that option, we would get 2 lines (1st and 3rd lines) and the INFO log would be output (the log says `2nd line was skipped because ...` for example).

```
a1,a2,a3
b1,b2
c1,c2,c3
```

I agree with adding this option, and welcome your PR.

**Comment by blackmo18** [comment]
Hello, I tried to implement the skipping of miss-matched number rows.

But I think it has some breaking changes, what I mean is somehow looks like a mess.
it's working but not very good I think.

[please give your thoughts here on my fork](https://github.com/blackmo18/kotlin-csv/commit/2db4c9d9ca1ec5195ce0c6e6d175b78e2ff3fa95#diff-7f66168a33ce49563b2de9fc1ea142ceR52), very much appreciated

**Comment by doyaaaaaken** [comment]
@blackmo18 I commented on your fork ✅
