### ISSUE TITLE
EROFS (Read-only file system)

### ISSUE THREAD

**Issue by aitizazsyed02** [doyaaaaaken/kotlin-csv#49]
getting this error please help
Caused by: java.io.FileNotFoundException: test.csv: open failed: EROFS (Read-only file system)

**Comment by doyaaaaaken** [comment]
Thank you.
Could you give me information about the bug?
For example,

* kotlin-csv version
* environment information (OS, jdk version, etc)
* describe the bug A clear and concise description of what the bug is.
* To Reproduce Steps to reproduce the behavior: (attach sample code)
* Screenshots If applicable, add screenshots to help explain your problem.

**Comment by aitizazsyed02** [comment]
- kotlin-csv version 0.9.0.
- java version 14
- I tried the exact same code provided in the README file as an example.
- Example used
val row1 = listOf("a", "b", "c")
val row2 = listOf("d", "e", "f")
csvWriter().open("test.csv") { 
    writeRow(row1)
    writeRow(row2)
    writeRows(listOf(row1, row2))
}

**Comment by doyaaaaaken** [comment]
I cannot reproduce the bug... Maybe, this link helps you.[https://stackoverflow.com/questions/27103877/java-io-filenotfoundexception-open-failed-erofs-read-only-file-system](java.io.FileNotFoundException: open failed: EROFS (Read-only file system)).
This article says it makes failure to save file in the root system partition which is always read-only.

**Comment by aitizazsyed02** [comment]
What's the location of a file where it will be saved using writeRows and writeAll?
how can we define our custom path?

**Comment by doyaaaaaken** [comment]
As you see [this line](https://github.com/doyaaaaaken/kotlin-csv/blob/master/src/jvmMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvWriter.kt#L19), the passed file name is simply converted to java.io.File.

Or, you can pass java.io.File instead of file name (String).
```
csvWriter().open(File("test.csv")) {
//...
}
```

**Comment by aitizazsyed02** [comment]
I have storage permission granted. but still this problem occurs. I have noticed it happen in android 10

**Comment by aitizazsyed02** [comment]
/storage/emulated/0/Documents/test.csv: open failed: ENOENT (No such file or directory)

**Comment by doyaaaaaken** [comment]
Sorry, I cannot do anything about java.io.File problem...
