### ISSUE TITLE
adding kotlin-csv-jvm depenedncy pulls testing libraries into runtime

### ISSUE THREAD

**Issue by kopernic-pl** [doyaaaaaken/kotlin-csv#56]
**Describe the bug**
When building application (using gradle distZip from application plugin) that depends on kotlin-csv, test libraries are pulled into created application artefact.

**To Reproduce**
Create empty basic kotlin project
add dependency implementation("com.github.doyaaaaaken:kotlin-csv-jvm:0.10.1")

**Expected behavior**
No testing libraries in artefact. To check:
- run `gradle dependencies`
    - runtimeClasspath should not contain kotlin-test library

- run `gradle distZip` with application plugin
    - created zip should not contain testing libraries

**Environment**
 - kotlin-csv: 0.10.1
 - java version: java8
 - gradle: 6.5
 - OS: Win

**Comment by doyaaaaaken** [comment]
Fixes successfully released at version 0.10.4
Thanks @kopernic-pl !! 🙇
