### ISSUE TITLE
Write in a Suspending function

### ISSUE THREAD

**Issue by doyaaaaaken** [doyaaaaaken/kotlin-csv#70]
Here, we can read in a suspending function.
https://github.com/doyaaaaaken/kotlin-csv#read-in-a-suspending-function
The background is here #66.

It would be better that we can also use `openAsync` on CSVWriter not only on CSVReader.

**Comment by blackmo18** [comment]
created pull request #73

**Comment by doyaaaaaken** [comment]
released at v0.14.0
