### ISSUE TITLE
Update to Kotlin 1.4.x

### ISSUE THREAD

**Issue by scrobbleme** [doyaaaaaken/kotlin-csv#74]
Hi,

Would be nice to see support for latest Kotlin 1.4

Thanks, 

Adrian

**Comment by doyaaaaaken** [comment]
Hi @scrobbleme
Thank you for your feedback! 😄 
I did it with the PR #75, and released it as v0.15.0.

BTW, you can also use kotlin-csv's existing version (<=0.14.0) from kotlin1.4 project.
In other words, you can stay your current kotlin-csv version or upgrade now.
