### ISSUE TITLE
Asci Null characters between csv Strings

### ISSUE THREAD

**Issue by AlexanderThiele** [doyaaaaaken/kotlin-csv#77]
Hey!
i've parsed a csv and found out, that there is an asci NULL character between every char.

i've used a httpRequest with a ByeInputStream as following:
```
val result = httpClient.get<HttpStatement> {
  url(blobUrl)
}.execute() { response: HttpResponse ->
  val channel: ByteReadChannel = response.receive()
  val byteIn = ByteArrayInputStream(channel.toByteArray())
  csvReader {
    delimiter = ','
    skipEmptyLine = true
    skipMissMatchedRow = true
  }.readAll(byteIn)
}
```
the output is a List<List<String>> which is totally correct.
```
// when i go through all elements like:
map { list ->
    list[0].forEach { c: Char ->
    println(c.toInt())
     }
}
```

```
// the output is:
0
50
0
48
0
50
0
49
0
45
0
48
0
49
0
45
0
48
0
49
0
```

This just happens to one csv response which i'm not sure why it happens. It's a report from the Google Play store
The same code works 100% good with other csv files.

i've solved it my replacing the NULL char manually like:

```
list[0].replace(Char.MIN_VALUE.toString(), "")

// e.g.
list[0].replace(Char.MIN_VALUE.toString(), "").forEach { c: Char ->
  println(c.toInt())
}
```

which returns:
```
50
48
50
49
45
48
49
45
48
49
```

i'm not sure if it's interesting to do it out of the box? 

have a nice day!

**Comment by doyaaaaaken** [comment]
Hi, @AlexanderThiele. Thank you for reporting.
I'm sorry, I couldn't figure it out. Is the Null character originally included in ByeInputStream?
If so, I think kotlin-csv should not do nothing about the Null character.

**Comment by AlexanderThiele** [comment]
Hey @doyaaaaaken 
i investigated this issue a bit more since it's only happening to one csv file and found out that this particular csv file is UTF-16 encoded 🤦‍♂️

i changed the charset: `charset = Charsets.UTF_16.name()`

works fine now!
