### ISSUE TITLE
Is there a way to alter existing csv file columns while reading from it?

### ISSUE THREAD

**Issue by akhattab451** [doyaaaaaken/kotlin-csv#85]
For example i have this csv file that includes a column formatted in json, and all i want to do is reformat that field per each row without having to rewrite the whole file

**Comment by doyaaaaaken** [comment]
@akhattab451 
Yes, you can do it with [`readAllAsSequence` feature](https://github.com/doyaaaaaken/kotlin-csv#read-as-sequence) or [`readLineByLine` feature](https://github.com/doyaaaaaken/kotlin-csv#read-line-by-line).
