### ISSUE TITLE
Handle duplicated headers

### ISSUE THREAD

**Issue by JulianSudendorf** [doyaaaaaken/kotlin-csv#90]
Hey @doyaaaaaken thank you very much for this library!

https://github.com/doyaaaaaken/kotlin-csv/blob/48510de1ce9856c672b5871c7363cf56f13633cf/src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt#L63-L64

When reading all lines with headers, a duplicate check is performed and `MalformedCSVException` thrown.
Since columns in a row are accessed by their index headers could simply be deduplicated by appending something like an occurrence indicator to the header name.

## Example:
| just | some | example | example | headers |
|------|------|---------|---------|---------|
| A    | B    | C       | D       | E       |

The header `example` appears twice. According to the suggestion the second occurrence could be named `example_01`.
Main benefit would be to not have a runtime exception thrown and not needing to rename columns in the original file to have it processed.

I know this would introduce some "magic" and I hope that wouldn't collide with your goal of having a simple library.
The required functionality would be just a few lines of code and I'd very gladly do a PR myself, just first wanted to get your thoughts on this.

**Comment by doyaaaaaken** [comment]
Hey @JulianSudendorf thank you very much for your feedback!
I totally agree with you.
We would be nice to introduce an option of CsvReader (ex. `autoRenameDuplicateHeaders: Boolean` ).
I'm waiting for your PR!

**Comment by doyaaaaaken** [comment]
released in v1.2.0
