### ISSUE TITLE
kotlin-csv.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.

### ISSUE THREAD

**Issue by jpnapps** [doyaaaaaken/kotlin-csv#93]
How to fix this issue ?

**Comment by doyaaaaaken** [comment]
I'm not sure, but If you were using the Kotlin 1.1.16, you should update it into 1.5.1.
An other person discussed about it.
https://stackoverflow.com/questions/67448034/module-was-compiled-with-an-incompatible-version-of-kotlin-the-binary-version
