### ISSUE TITLE
Remove logger 3rd party library

### ISSUE THREAD

**Issue by vanniktech** [doyaaaaaken/kotlin-csv#94]
Quickly looking at the code it seems like there's only one log statement:

https://github.com/doyaaaaaken/kotlin-csv/blob/8108e5bcc24d55d813868ca3a238aed59a16b628/src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt#L48

Do we really need to pull an entire library for logging?

https://github.com/doyaaaaaken/kotlin-csv/blob/ed7a6783313b3d033f3ffe702227b7a3961bc72b/build.gradle.kts#L50

I'm an Android user and currently that log would go basically nowhere.

**Comment by vanniktech** [comment]
I'd propose to remove that log statement. If you're using `skipMissMatchedRow` you're kind of expecting this behavior.

**Comment by doyaaaaaken** [comment]
Thanks for the feedback. 👍  I'll consider it in a short time.

**Comment by doyaaaaaken** [comment]
Hi, @vanniktech, thank you for your useful feedback.

In conclusion, I would like to leave this library dependency as it is.

At first, I think It would be nice to replace the dependency for `kotlin-logger` with that for `slf4j`, but I can't do it because `kotlin-csv` is multiplatform library.
Then, I consider simply removing `kotlin-logger`, but decide to keep it because logging is an important element for CSV read/write because it is a complex use case that requires debugging.

**Comment by vanniktech** [comment]
> kotlin-csv is multiplatform library.

and that's good!

> Then, I consider simply removing `kotlin-logger`, but decide to keep it because logging is an important element for CSV read/write because it is a complex use case that requires debugging.

But then would you want to use a debugger instead of a log statement that goes possibly nowhere, right?

**Comment by doyaaaaaken** [comment]
I see what you're saying, but [this log message](https://github.com/doyaaaaaken/kotlin-csv/blob/8108e5bcc24d55d813868ca3a238aed59a16b628/src/commonMain/kotlin/com/github/doyaaaaaken/kotlincsv/client/CsvFileReader.kt#L48) is very important information for users of the `skipMissMatchedRow` option.
As of now, I use the kotlin-logger at only one statement, but we would probably use it at other statements in the future.
So, I would like to leave it for now.

**Comment by vanniktech** [comment]
Okay but then would not it be better to have our own `Logger` interface which - if you want logging, you can pass your own instance and to the logging you'd need - and otherwise you're not bothered by it?

**Comment by doyaaaaaken** [comment]
Sounds like a good idea.
If you have an image of how you would implement it, I would welcome a pull request if you like.

**Comment by doyaaaaaken** [comment]
Released in version 1.4
