### ISSUE TITLE
Write directly to a String

### ISSUE THREAD

**Issue by yamin8000** [doyaaaaaken/kotlin-csv#97]
is there any way to write to a String instead of a File?

**Comment by yamin8000** [comment]
> Sorry, this library supports output formats only as java.io.File or OutputStream.

The preference of only outputting to a `File` or `OutputStream` seems somewhat opinionated or even questionable to me.
It can be beneficial to output directly to a `String` like when you want to send data in Android to other apps or share data using `Intent` or hell this library is so easy to use and usable one can use it for raw-printing database records in logs or a `TextView` for testing purposes or even usable in back-end programming and you just want to respond to an `API` call with a `CSV` representation of some data records from the database, that's just my two cents.
For now, I can live with writing to a temporary file in the cache and read that same file so I can have it as a `String`.

**Comment by doyaaaaaken** [comment]
Thanks for the feedback.
I think it's a good idea. I'll consider addressing this issue.

> For now, I can live with writing to a temporary file in the cache and read that same file so I can have it as a String.

Yes, it's a valid workaround for this problem.

**Comment by Thijsiez** [comment]
Not sure if this would work for your use case, but maybe writing an extension function that does something like the following would be helpful
`val output = String(outputStream.toByteArray(), Charsets.UTF_8)`

**Comment by doyaaaaaken** [comment]
@Thijsiez Good solution!! Thanks!

**Comment by doyaaaaaken** [comment]
Released in [version 1.6.0](https://github.com/doyaaaaaken/kotlin-csv/releases/tag/1.6.0).
Thanks, @Thijsiez !! 😄
